Repository iteahome/team-project-online-shop, pull requests merged in 2020-02, with the labels that each got.

#47 created productdao and create and find all methods within
  .idea/.gitignore
  out/production/team-project-online-shop/com/shop/OnlineShop.class
  out/production/team-project-online-shop/com/shop/dao/ProductDAO.class
  src/main/java/com/shop/dao/ProductDAO.java
Labels: DAO

#48 created productService and its methods addproduct and filterproduct, …
  src/main/java/com/shop/dao/ProductDAO.java
  src/main/java/com/shop/model/Product.java
  src/main/java/com/shop/service/ProductService.java
  src/main/resources/products.txt
Labels: service

#59 Created basic AdminShopUI and added a new method to be used instead o…
  src/main/java/com/shop/datahandlers/formatter/PrintUI.java
  src/main/java/com/shop/ui/AdminShopUI.java
Labels: UI

#62 Rewriting 01
  .idea/team-project-online-shop.iml
  src/main/java/com/shop/OnlineShop.java
  src/main/java/com/shop/dao/FileEdit.java
  src/main/java/com/shop/dao/ProductDAO.java
  src/main/java/com/shop/dao/UserDAO.java
  src/main/java/com/shop/datahandlers/formatter/InputPopUps.java
  src/main/java/com/shop/model/Product.java
  src/main/java/com/shop/model/User.java
  src/main/java/com/shop/security/UserContext.java
  src/main/java/com/shop/service/ProductService.java
  src/main/java/com/shop/service/UserService.java
  src/main/java/com/shop/ui/AdminManageAccountsUI.java
  src/main/java/com/shop/ui/AdminShopUI.java
  src/main/java/com/shop/ui/LoginUI.java
  src/main/java/com/shop/ui/MainUI.java
  src/main/java/com/shop/ui/ShopUI.java
  src/main/java/com/shop/ui/SignUpUI.java
  src/main/java/com/shop/ui/ui_handlers/InputPopUps.java
  src/main/java/com/shop/ui/ui_handlers/PrintUI.java
  src/main/resources/products.txt
  src/main/resources/users.txt
Labels: High_Priority

#66 resolved permanent pop_Up. Defined universal Cancel
  src/main/java/com/shop/dao/ProductDAO.java
  src/main/java/com/shop/ui/AdminManageAccountsUI.java
  src/main/java/com/shop/ui/AdminShopUI.java
  src/main/java/com/shop/ui/LoginUI.java
  src/main/java/com/shop/ui/MainUI.java
  src/main/java/com/shop/ui/ShopUI.java
  src/main/java/com/shop/ui/SignUpUI.java
  src/main/java/com/shop/ui/ui_handlers/InputPopUps.java
Labels: enhancement

#74 created products list
  src/main/resources/products.txt
Labels: DAO

#72 Validate email
  src/main/java/com/shop/datahandlers/validator/EmailValidator.java
Labels: datahandler

#76 implemented email validator on sign up
  src/main/java/com/shop/datahandlers/validator/EmailValidator.java
  src/main/java/com/shop/ui/SignUpUI.java
Labels: Implement

#78 created phone validator class
  src/main/java/com/shop/datahandlers/validator/PhoneValidator.java
Labels: datahandler

#79 Sprint1
  src/main/java/com/shop/Application.java
  src/main/java/com/shop/OnlineShop.java
  src/main/java/com/shop/cache/ProductCache.java
  src/main/java/com/shop/dao/FileEdit.java
  src/main/java/com/shop/dao/FileUtil.java
  src/main/java/com/shop/dao/ProductDAO.java
  src/main/java/com/shop/dao/UserDAO.java
  src/main/java/com/shop/exception/ProductNotFoundException.java
  src/main/java/com/shop/model/Cart.java
  src/main/java/com/shop/model/Product.java
  src/main/java/com/shop/model/User.java
  src/main/java/com/shop/model/Writable.java
  src/main/java/com/shop/security/CartContext.java
  src/main/java/com/shop/security/UserContext.java
  src/main/java/com/shop/service/CartService.java
  src/main/java/com/shop/service/ProductService.java
  src/main/java/com/shop/service/UserService.java
  src/main/java/com/shop/ui/AdminManageAccountsUI.java
  src/main/java/com/shop/ui/AdminShopUI.java
  src/main/java/com/shop/ui/LoginUI.java
  src/main/java/com/shop/ui/MainUI.java
  src/main/java/com/shop/ui/ShopUI.java
  src/main/java/com/shop/ui/SignUpUI.java
  src/main/java/com/shop/ui/UserAccountUI.java
  src/main/java/com/shop/ui/UserShopUI.java
  src/main/java/com/shop/ui/handlers/InputPopUps.java
  src/main/java/com/shop/ui/handlers/PrintUI.java
  src/main/java/com/shop/ui/ui_handlers/InputPopUps.java
  src/main/java/com/shop/ui/validator/EmailValidator.java
  src/main/java/com/shop/ui/validator/PhNoFormat.java
  src/main/java/com/shop/ui/validator/PhoneValidator.java
  src/main/resources/product_seq.txt
  src/main/resources/products.txt
  src/main/resources/users.txt
Labels: Sprint

#80 Sprint2
  src/main/java/com/shop/cache/ProductCache.java
  src/main/java/com/shop/dao/FileEdit.java
  src/main/java/com/shop/model/User.java
  src/main/java/com/shop/security/CartContext.java
  src/main/java/com/shop/service/CartService.java
  src/main/java/com/shop/service/ProductService.java
  src/main/java/com/shop/service/UserService.java
  src/main/java/com/shop/ui/CartUI.java
  src/main/java/com/shop/ui/UserAccountUI.java
  src/main/java/com/shop/ui/UserShopUI.java
  src/main/java/com/shop/ui/validator/PhNoFormat.java
  src/main/java/com/shop/ui/validator/PhoneNoValidator.java
  src/main/java/com/shop/ui/validator/PhoneValidator.java
  src/main/resources/users.txt
Labels: Sprint
